// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPwPsP7HcQXKURZVslY5O0sR7EbEIqLA',
    appId: '1:583527128111:web:332ba334db0c93c132bada',
    messagingSenderId: '583527128111',
    projectId: 'kory-care',
    authDomain: 'kory-care.firebaseapp.com',
    storageBucket: 'kory-care.appspot.com',
    measurementId: 'G-B30GGBMPH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChy1LwrL26Dxfmaol8DBBItgcjiy0bn7k',
    appId: '1:583527128111:android:8918ea1f7c20097832bada',
    messagingSenderId: '583527128111',
    projectId: 'kory-care',
    storageBucket: 'kory-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDS62MSpOb2SavoP0mQKTxWEz9Nfm4ks',
    appId: '1:583527128111:ios:b8c112f95f21ea7932bada',
    messagingSenderId: '583527128111',
    projectId: 'kory-care',
    storageBucket: 'kory-care.appspot.com',
    androidClientId: '583527128111-tj0j94g9fe6v4ihpn9cp712uj1jo57uv.apps.googleusercontent.com',
    iosClientId: '583527128111-4duig5s4qeukptto3u8ljh2qn7dus0mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );
}
